# Generated by Django 5.0.7 on 2024-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('devStudio', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('avgRating', models.FloatField()),
                ('numOfReviews', models.IntegerField()),
            ],
        ),
    ]
